### ISSUE TITLE
Add `<details>` and `<summary>` elements

### ISSUE THREAD

**Issue by chasefleming** [chasefleming/elem-go#119]
## Issue

We need add support for the following elements:

- `<details>`
- `<summary>`

## Requirements

- [ ] Add these to the [elements.go file (under the "Semantic Elements" section)](https://github.com/chasefleming/elem-go/blob/main/elements.go#L261) and follow Go naming conventions
- [ ] Add tests for each to ["Semantic Elements" section of elements_test.go](https://github.com/chasefleming/elem-go/blob/main/elements_test.go#L328)

**Comment by dreth** [comment]
Hey @chasefleming!, these are already present in the library:

https://github.com/chasefleming/elem-go/blob/394d31065a2de74c930f0e71c40854497824feac/elements.go#L371

https://github.com/chasefleming/elem-go/blob/394d31065a2de74c930f0e71c40854497824feac/elements.go#L412

Do you simply mean to move them to that section?

**Comment by chasefleming** [comment]
You're right, apologies. I'll just update the readme then.
