### ISSUE TITLE
Add Missing Flexbox Properties

### ISSUE THREAD

**Issue by chasefleming** [chasefleming/elem-go#13]
## Issue

Add missing properties related to the Flexbox layout model in the following file: https://github.com/chasefleming/elem-go/blob/main/styles/styles.go

## Properties to be added
- flex-grow
- flex-shrink
- flex-basis
- align-self

**Comment by MhmoudGit** [comment]
Can I take on this issue? I'm new to contributing.

**Comment by chasefleming** [comment]
Absolutely! Go for it @MhmoudGit . Assigning you. Thanks.

**Comment by MhmoudGit** [comment]
Thanks, I already made the PR would appreciate if you reviewed it @chasefleming

**Comment by chasefleming** [comment]
Reviewed. Looks good. Thanks!
