### ISSUE TITLE
Add Time Duration Utility

### ISSUE THREAD

**Issue by chasefleming** [chasefleming/elem-go#136]
CSS animation durations can have ms or s suffixes to denote time.

For example:

```
animation-duration: 10s, 35s, 230ms;
```

Create a utility function in the [styles package utils file](https://github.com/chasefleming/elem-go/blob/main/styles/utils.go), alongside the other utilities, to handle these time options:

```
Seconds(10) // takes float64, returns string
Seconds(10.5) // takes float64, returns string
Milliseconds(230) // takes int
```

Ensure to include tests for these functions.

**Comment by BreakTos** [comment]
can i try this ?
