### ISSUE TITLE
Add Missing Grid Style Properties

### ISSUE THREAD

**Issue by chasefleming** [chasefleming/elem-go#14]
## Issue

Add missing properties related to the Grid layout model.

## Properties to be added

- grid-template-rows
- grid-template-columns
- grid-gap
- Advanced properties (e.g., grid-auto-rows, grid-auto-columns, grid-auto-flow)

**Comment by Paul-Annay** [comment]
hey there, I would like to work on this....

**Comment by chasefleming** [comment]
Great, thanks @Paul-Annay ! Assigning you.
