### ISSUE TITLE
Add `hsl` and `hsla` Function Implementations

### ISSUE THREAD

**Issue by chasefleming** [chasefleming/elem-go#140]
Add support for `hsl` and `hsla` colors to the [style utilities](https://github.com/chasefleming/elem-go/blob/main/styles/utils.go). The function signatures should be as follows:

```go
func HSL(h, s, l int) string
func HSLA(h, s, l int, a float64) string
```

Also, make sure to [add tests here](https://github.com/chasefleming/elem-go/blob/main/styles/stylemanager_test.go).

**Comment by bsushmith** [comment]
I have created a PR for this - https://github.com/chasefleming/elem-go/pull/141.
