### ISSUE TITLE
Add Missing htmx Attributes 

### ISSUE THREAD

**Issue by chasefleming** [chasefleming/elem-go#25]
## Description:

The current Go package for `htmx` is missing several attributes that are present in the htmx library. These attributes are crucial for leveraging the full power and flexibility of htmx.

## Missing Attributes:

1. **Request Headers and Content-Type**:
   - `hx-headers`: Specifies additional headers for the request.
   - `hx-content`: Specifies how the content should be encoded.

2. **Request Timeout and Retries**:
   - `hx-timeout`: Specifies a timeout, in milliseconds, for the request.
   - `hx-retry`: Provides a mechanism to retry requests.
   - `hx-retry-timeout`: Specifies how long, in milliseconds, to wait in between retries.

3. **Events**:
   - `hx-on`: Specifies JavaScript to be executed in response to htmx events.

4. **History**:
   - `hx-history-elt`: Specifies an alternate element to use for history purposes.
   - `hx-history-attr`: Specifies the attribute to use when pulling values for history purposes.

5. **Response Processing**:
   - `hx-select`: Selects content from the response for swapping.
   - `hx-ext`: Specifies extensions to activate for the element.
   - `hx-vals`: Specifies values for the request.

6. **Caching**:
   - `hx-cache`: Provides control over AJAX request caching.

7. **Miscellaneous**:
   - `hx-triggering-element`: Gets set to the element that triggered the current request.
   - `hx-triggering-event`: Gets set to the event that triggered the current request.

**Comment by AxelRHD** [comment]
I can't produce any working code for `hx-vals`. As far as I can see, HTMX is expecting a JSON object with double quotes, surrounded by single quotes.

**Comment by chasefleming** [comment]
Does this code work for you @AxelRHD ?

```go
content := elem.Div(attrs.Props{
    htmx.HXGet:  "/example",
    htmx.HXVals: `'{"myVal": "My Value"}'`,
}, elem.Text("Get Some HTML, Including A Value in the Request"))

dynamicContent := elem.Div(attrs.Props{
    htmx.HXGet:  "/example",
    htmx.HXVals: `'js:{myVal: calculateValue()}'`,
}, elem.Text("Get Some HTML, Including a Dynamic Value from Javascript in the Request"))
``

**Comment by AxelRHD** [comment]
> Does this code work for you @AxelRHD ?
> 
> ```go
> content := elem.Div(attrs.Props{
>     htmx.HXGet:  "/example",
>     htmx.HXVals: `'{"myVal": "My Value"}'`,
> }, elem.Text("Get Some HTML, Including A Value in the Request"))
> 
> dynamicContent := elem.Div(attrs.Props{
>     htmx.HXGet:  "/example",
>     htmx.HXVals: `'js:{myVal: calculateValue()}'`,
> }, elem.Text("Get Some HTML, Including a Dynamic Value from Javascript in the Request"))
> ```

That works. Thanks a lot!

**Comment by chasefleming** [comment]
Awesome, I'll update the docs as well @AxelRHD . Thanks for letting me know that wasn't clear.

**Comment by AxelRHD** [comment]
I haven't tested with JSON marshaling yet. But that would also be a good real life example.

**Comment by chasefleming** [comment]
@AxelRHD what do you think about there actually being a method for simplifying the setting of JSON as an attribute value? Something like this:

```go
data := MyData{
        Key:   "example",
        Value: 123,
    }

    content := elem.Div(attrs.Props{
        attrs.ID:   "my-div",
        attrs.Data: attrs.JSONData(data),
    }, elem.Text("Content"))
    ```
