### ISSUE TITLE
Question - missing Style Sheet

### ISSUE THREAD

**Issue by chrismalek** [chasefleming/elem-go#27]
I could very well be blind.

I do not see a way to insert a "link" in the head

```html
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
```

What am I missing?

**Comment by chrismalek** [comment]
I answered my own question. It looks like you can generate any element by passing in the element name as a string.

```go

bulma := elem.NewElement("link", elem.Attrs{attrs.Rel: "stylesheet", attrs.Href: "https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.3/css/bulma.min.css"})
```

**Comment by chasefleming** [comment]
@chrismalek That's one way to do it! You're also not blind. `Link` should be added so you don't have to write a string. Oversight on our part. I will make a PR to add it and get a release out for you shortly. Thanks for bringing it to our attention. Let me know if you there is anything else you need.

**Comment by chrismalek** [comment]
Ditto the following elements.

- footer
- nav
- section


I am building out a new app with bulma and this framework and noticed those missing where I used used elem.NewElement("whatever"....

**Comment by chasefleming** [comment]
@chrismalek I've added what you need and released. You just need to upgrade to `v0.7.0`. See the release notes here: https://github.com/chasefleming/elem-go/releases/tag/v0.7.0

Thanks again for letting us know what you need! Very helpful. Always feel free to add an issue for any other feedback or needs you have.

**Comment by chrismalek** [comment]
Looks great..thanks.  👍🏻 😄
