### ISSUE TITLE
Add Semantic Text Content Elements

### ISSUE THREAD

**Issue by chasefleming** [chasefleming/elem-go#30]
## Description

Support needs to be added for the following semantic text content elements:

- `<figure>`: Represents content, such as illustrations, diagrams, photos, etc.
- `<figcaption>`: Represents a caption or legend for a `<figure>`.
- `<mark>`: Denotes highlighted or emphasized text.
- `<time>`: Denotes a specific period in time or a duration.
- `<details>`: Represents a disclosure widget for hiding and showing details.
- `<summary>`: Represents a summary, heading, or legend for the content within `<details>`.
- `<address>`: Denotes the contact information for its nearest `<article>` or `<body>` ancestor.

## Requirements

- These additions should be placed under a new subsection, called "Text Content," within the "Semantic Elements" section of this file: https://github.com/chasefleming/elem-go/blob/main/elements.go#L159
- Tests should be added for each here (but also under a new subsection): https://github.com/chasefleming/elem-go/blob/main/elements_test.go#L223
- Update the readme with the new elements

**Comment by chrismalek** [comment]
While you are adding these can you also add "i".

For Font Awesome.

`<i class="fa-regular fa-face-smile"></I>`


I have been having to do this (different icon).

`elem.NewElement("i", elem.Attrs{attrs.Class: "fa-solid fa-unlock-keyhole fa-lg"}),`

**Comment by chasefleming** [comment]
@chrismalek Great call, we'll add that. I've made a separate ticket for it here: https://github.com/chasefleming/elem-go/issues/31

We'll get it in the next release.

Can't wait to see what you're building! Hope you share your project when you're done so we can see it :)

**Comment by chasefleming** [comment]
By the way @chrismalek , looks like in Font Awesome you can also use `<span>` instead of `<i>`. But either way the next release with what you need will be soon.

**Comment by chasefleming** [comment]
@chrismalek `v0.8.0` is now released and has the element you need: https://github.com/chasefleming/elem-go/releases/tag/v0.8.0

**Comment by chrismalek** [comment]
Using it now..thanks so much.
