### ISSUE TITLE
Add Support for <i> Element

### ISSUE THREAD

**Issue by chasefleming** [chasefleming/elem-go#31]
## Description

- Add the `<i>` element, which is commonly used for embedding icons, especially with libraries like FontAwesome.
- Update the documentation (README) to include the `<i>` element in the list of supported elements, with emphasis on its use for icon embedding.
- Create a test for it

## Use Case

The `<i>` element, when used with icon libraries like FontAwesome, can represent various icons, such as:

`<i class="fa-regular fa-face-smile"></i>`

**Comment by u5surf** [comment]
@chasefleming 
Hi, can you assign me? I would like to work on this issue.

**Comment by chasefleming** [comment]
Thanks @u5surf ! Assigning you. And yes please, let's do it according to the MDN spec. Sorry if the issue description was not clear. Thanks for clarifying.
