### ISSUE TITLE
Optimize Style Type's String Method with `strings.Builder`

### ISSUE THREAD

**Issue by chasefleming** [chasefleming/elem-go#34]
The current implementation of the `String` method in the `Style` type uses string concatenation which can lead to multiple memory allocations, especially for styles with a large number of properties. For better performance, switch to `strings.Builder`.

See this line for context: https://github.com/chasefleming/elem-go/blob/main/utils.go#L19

**Comment by Khusyasy** [comment]
Hello @chasefleming , I'm interested to help on this issue

**Comment by chasefleming** [comment]
Thanks @Khusyasy ! I've assigned you.
