### ISSUE TITLE
Add Support for Outline Style Properties

### ISSUE THREAD

**Issue by chasefleming** [chasefleming/elem-go#36]
## Description

The `styles` package needs support various outline properties. Add them to here under "Box Model:" https://github.com/chasefleming/elem-go/blob/2b7e1d671ae12e5f272770d51c8801b28d970a94/styles/styles.go#L44C3-L44C3

## Properties to Add

- `outline`
- `outline-style`
- `outline-color`
- `outline-width`
- `outline-offset`

**Comment by whisk** [comment]
Hi @chasefleming, please consider PR #37
