### ISSUE TITLE
Add Support for Additional Font & Text Style Properties

### ISSUE THREAD

**Issue by chasefleming** [chasefleming/elem-go#38]
## Description

The `styles` package needs support various font and text properties. Add them to here under "Font & Text Properties:" https://github.com/chasefleming/elem-go/blob/2b7e1d671ae12e5f272770d51c8801b28d970a94/styles/styles.go#L84

## Properties to Add

- `font-style`
- `text-shadow`
- `vertical-align`
- `word-spacing`
- `word-break`
- `text-indent`

**Comment by Emm-dev0** [comment]
I would like to work on this, can you assign it to me

**Comment by chasefleming** [comment]
Assigned. Thanks @Emm-dev0 !

**Comment by Emm-dev0** [comment]
Working on it.

**Comment by Emm-dev0** [comment]
Please review the pull request, I am finished. Thanks
