### ISSUE TITLE
Add Missing List Items

### ISSUE THREAD

**Issue by chasefleming** [chasefleming/elem-go#4]
## Issue

The library currently supports `ul` and `li` elements. But, there are some other standard HTML list-related elements that should be included.

## Description
 
To make the library more holistic and provide developers with a broader range of list options, we should add the following elements:

- `<ol>`: Ordered list.
- `<dl>`: Description list.
- `<dt>`: Description term. Represents the term in a key-value pair in a `<dl>`.
- `<dd>`: Description description. Represents the value in a key-value pair in a `<dl>`.

**Comment by lemorage** [comment]
I can work on this issue🙂

**Comment by chasefleming** [comment]
That would be great @lemorage . Thank you! Assigning you to the issue.
