### ISSUE TITLE
Add Additional Visual Properties in the `styles` package

### ISSUE THREAD

**Issue by chasefleming** [chasefleming/elem-go#40]
## Description

The `styles` package needs support additional visual properties. Add them to here under "Visual Properties:" https://github.com/chasefleming/elem-go/blob/2b7e1d671ae12e5f272770d51c8801b28d970a94/styles/styles.go#L98

## Properties to Add

- `background-position`
- `background-attachment`
- `background-blend-mode`
- `backface-visibility`
- `perspective`
- `transform-origin`

**Comment by sidd3103** [comment]
Hello. Created PR for this

**Comment by chasefleming** [comment]
Thanks for grabbing it @sidd3103 !
