### ISSUE TITLE
Add Table Attributes to `attrs` Package

### ISSUE THREAD

**Issue by chasefleming** [chasefleming/elem-go#41]
## Description

The `styles` package needs support table attributes. Add them to here in a new category called "Table Attributes": https://github.com/chasefleming/elem-go/blob/main/attrs/attrs.go

## Properties to Add

- `colspan`
- `rowspan`
- `headers`
- `scope`

**Comment by sidd3103** [comment]
Hello. Created a PR for this

**Comment by chasefleming** [comment]
Great, thanks @sidd3103 !
