### ISSUE TITLE
Add `<iframe>` Element Support

### ISSUE THREAD

**Issue by chasefleming** [chasefleming/elem-go#45]
## Description

- Add support for `<iframe>` element under a new section called "Embedded Content" in `elements.go`
- In the `attrs` package add the following attributes for `iframe` support:
    - Under "Universal Attributes":
        - `loading`
    - Under a new category called "IFrame Attributes":
        - `allow`
        - `allowfullscreen`
        - `csp`
        - `referrerpolicy`
        - `sandbox`
        - `srcdoc`
         
## Requirements

- Test the `<iframe>` element's rendering with various attributes to ensure correct behavior.
- Update readme so the new element is added to the "Supported" list

**Comment by Malay-dev** [comment]
Hey @chasefleming,  I would like to work on this issue... Please assign it to me..

**Comment by chasefleming** [comment]
Great, thanks @Malay-dev ! I've assigned you.

**Comment by chasefleming** [comment]
@Malay-dev are you still working on this?

**Comment by Malay-dev** [comment]
**Thank you** @chasefleming.... It was a pleasure working on this project... First Go language contribution :blush:

**Comment by chasefleming** [comment]
Awesome, congrats @Malay-dev ! Will post some more issues soon if you feel like contributing any more. Thanks again!
