### ISSUE TITLE
Attributes With "false" Values Should Not Be Added Element

### ISSUE THREAD

**Issue by chasefleming** [chasefleming/elem-go#48]
## Description

Some attributes inherently signify a `true` value merely by their presence, and attempting to set them to `"false"` may not yield the expected result. For instance, consider the following code snippet, which will still display as checked:

```
checkbox := Input(Attrs{
    "type":    "checkbox",
    "checked": "false",
})
```

The challenge arises when a developer wants to explicitly set an attribute to `false` to avoid creating multiple attribute sets with conditionals. To address this, we need to modify the behavior so that when an attribute's value is `"false", it is omitted from the rendered output. Furthermore, if an attribute has an empty string value, it should be rendered without any value.

## Expected Output

- `checkbox` should render as `<input type="checkbox" checked>` if `"true"`
- `checkbox` should render as `<input type="checkbox">` if `"false"` or and empty string.

## Tasks

- Implement the necessary changes in the `elem.go` code.
- Create unit tests to validate all scenarios, including input examples of `"true"`, `"false"`, and an empty string.
- ~~Update the project README to include a note highlighting that attribute values set to `"false"` will be omitted in the rendered output.~~

**Comment by whisk** [comment]
Hi @chasefleming, i would like to work on this issue. Could you please assign it to me?

**Comment by chasefleming** [comment]
That would be great. Thanks @whisk ! Assigned you.

**Comment by chasefleming** [comment]
@whisk I'm removing the task about updating the readme. Let's just make the code changes. I need to think more about how that would work with the existing documentation since it might require a new section.

**Comment by whisk** [comment]
Thanks @chasefleming! Please see my PR #49
