### ISSUE TITLE
Question - <html data-theme="cupcake"></html>

### ISSUE THREAD

**Issue by chrismalek** [chasefleming/elem-go#73]
I am working with DaisyUI.

There is a requirement to set a color scheme like this:

`<html data-theme="cupcake"></html>`

I can't figure out how to do that with this library.  Am I missing something? 

PS: Please consider opening up the GitHub discussions on this. I always think that asking a question should be under discussions and reporting a real issue under issues.

**Comment by whisk** [comment]
Hi @chrismalek, consider using something like this:
```
Html(attrs.Props{attrs.DataPrefix + "theme": "cupcake"}, Text("foobar"))
```
Here `attrs.DataPrefix + "theme"` is your attribute name.

@chasefleming, what do you think about introducing a new method like `DataAttr(suffix string) string` to generate data-attributes names?

**Comment by chasefleming** [comment]
Yep @whisk is correct. That should work. Your attribute key could also just be a string, but it's recommend using constants for type safety. But I agree @whisk, a function for data attributes would be much better. We should add that and maybe drop `DataPrefix` all together as an option since it doesn't follow the same naming conventions and a function is a much better way to do it. Are you interested in taking that issue?

**Comment by whisk** [comment]
@chasefleming, you could assign this to me.
Though I think we should keep `DataPrefix` until the next major update, since removing it would be a breaking change.

**Comment by chasefleming** [comment]
Sounds good @whisk . Let's leave it in. Also, do you mind putting this in a new `utils.go` file in the `attrs` subpackage with a `utils_test.go` as well. Thanks!

**Comment by whisk** [comment]
Hi @chasefleming, please check PR #78

**Comment by chrismalek** [comment]
Sorry late to the game here.  I must have needed more coffee. Of course this would work as well 
`Html(attrs.Props{attrs.DataPrefix + "theme": "cupcake"}, Text("foobar"))` it is just string concatenation.

**Comment by chasefleming** [comment]
Yep, that will work @chrismalek , but the version @whisk is putting in will be more performant than string concatenation if you're rendering a decent amount of elements with attributes. So it will be recommended to use that once it's out. Probably next release.
