### ISSUE TITLE
QR codes

### ISSUE THREAD

**Issue by gedw99** [chasefleming/elem-go#74]
I have a need to take the HTML to PDF and embed a QR code that links back to the page.

The use case is an Art portfolio site for a friend. She needs the HTML to show each art piece with some text etc, and to have a PDF of that page with a QR code on it.

the idea is that she can hand them out at her fairs if someone likes a piece, and the can later just scan the QR code and be taken to the web page.

https://github.com/benoitkugler/go-weasyprint looks like it will do it in native go. 
The traditional way is a chrome embedded render I think which I would like to avoid.

**Comment by chasefleming** [comment]
You can embed the QR code in your HTML content like this:

```go
qrCode := elem.Img(attrs.Props{attrs.Src: "qr_code_image_url"})
artPieceWithQR := elem.Div(nil, artPiece, qrCode)
```

Then, render the HTML content to a string:

```go
htmlContent := artPieceWithQR.Render()
// Now use this HTML content with a PDF conversion library
```

Does this answer your question?

**Comment by gedw99** [comment]
yes that helps get me rolling @chasefleming 

thank you !!
