### ISSUE TITLE
Add support for `step` attribute.

### ISSUE THREAD

**Issue by BenB196** [chasefleming/elem-go#79]
HTML Input supports the [`step`](https://www.w3schools.com/tags/att_input_step.asp) attribute, but it doesn't appear that this is currently supported by this package.

**Comment by chasefleming** [comment]
Thanks for pointing this out @BenB196 . We'll get this added to the next release. In the meantime, you can still pass a string to `attrs.Props` for the key for `"step"` and then when the release comes out switch to the type-safe version. Thanks again for making the issue!
