### ISSUE TITLE
broadcast and sync

### ISSUE THREAD

**Issue by gedw99** [chasefleming/elem-go#85]
[github.com/anycable/anycable-go](https://github.com/anycable/anycable-go) looks like a nice match with go-elem. It's designed for Turbo, but it will work with go-elem and htmx and SSE / Web Sockets.

It can also embed the NATS Server for you.

https://dev.to/chasefleming/building-a-counter-app-with-htmx-go-fiber-and-elem-go-9jd looks good too @chasefleming

**Comment by chasefleming** [comment]
Thanks @gedw99 , working on some more tutorials. Coming soon.

**Comment by chasefleming** [comment]
Closing this. Was thinking about opening a GitHub Discussion board on here soon for more ongoing topics like this that are more for conversations around the library as opposed to specific issues. Let me know if you'd find that useful. Thanks!

**Comment by gedw99** [comment]
Discussion is a good idea

**Comment by chasefleming** [comment]
@gedw99 The discussions tab has been added! https://github.com/chasefleming/elem-go/discussions
