### ISSUE TITLE
Make `NewElement` Function Private for Better Encapsulation

### ISSUE THREAD

**Issue by chasefleming** [chasefleming/elem-go#93]
Currently, the `NewElement` function in the `elem-go` library is public. This exposes internal implementation details that users of the library do not need to interact with directly. To improve the encapsulation and maintain a clean public API, the `NewElement` function be made private.

#### Proposed Change

- Rename the `NewElement` function to `newElement`.
- Update all internal uses of `NewElement` within the library to reference `newElement`.

#### Benefits

- **Encapsulation**: Making `newElement` private hides internal details from the library users, promoting better encapsulation.
- **API Clarity**: Ensures that the public API remains clear and focused, guiding users towards intended usage patterns.
- **Maintenance**: Simplifies future maintenance of the library by reducing the publicly exposed surface area.

**Comment by webstradev** [comment]
I'm happy to pick this up

**Comment by chasefleming** [comment]
Great, thanks for grabbing it @webstradev !
