### ISSUE TITLE
Implement `RenderWithOptions` Method for Custom Render Options

### ISSUE THREAD

**Issue by chasefleming** [chasefleming/elem-go#96]
`Render` now adds the preamble as noted in #91 , `<!DOCTYPE html>` by default. While this is the most common scenario, there may still be other environments where this is not desired. We should still offer an option to disable this if necessary. In order to keep `Render()` simple and to not break backwards compatibility we should add a new method called `RenderWithOptions` that takes a custom param of `RenderOptions` with a flag to `DisablePreamble` if desired. We could also use this to later allow less common preambles to be applied. 

## Example Usage

```go
options := RenderOptions{DisablePreamble: true}
htmlString := myHtmlElement.RenderWithOptions(options)
```

**Comment by AKARSHITJOSHI** [comment]
Do you expect RenderWithOptions to pass the DisablePreable to RenderTo https://github.com/chasefleming/elem-go/blob/72ae0178f74d9bfef61afd139c2dc0b1145adb27/elem.go#L114 and then put a check at 
https://github.com/chasefleming/elem-go/blob/72ae0178f74d9bfef61afd139c2dc0b1145adb27/elem.go#L118 for handling preamble ?

**Comment by whisk** [comment]
Hi @chasefleming! I made a draft PR for this issue to figure out how this changes may look like. Please see #97 .
I changed `RenderTo` signature to incorporate the options. Though `RenderTo` is technically a public method, I don't see it's described in docs. Also`elem-go` is in development itself, so I felt free to change it.

**Comment by chasefleming** [comment]
Thank you! I was actually going to make an issue about changing `RenderTo` to a private method. We shouldn't expose it.

**Comment by chasefleming** [comment]
I created a separate issue to address the `RenderTo` being exposed. Doesn't need to be addressed in the PR, but wanted to make sure it was tracked for the next release notes: https://github.com/chasefleming/elem-go/issues/98
